### ISSUE TITLE
Back-End Testing Checklist for iteration 1

### ISSUE THREAD

**Issue by kimmichurri** [JustinTorrance/notez#12]

**Comment by kimmichurri** [comment]
- [ ] test GET
    - [ ] happy
    - [ ] sad

- [ ] test POST
    - [ ] happy
    - [ ] sad

- [ ] test PUT
    - [ ] happy
    - [ ] sad

- [ ] test PATCH
    - [ ] happy
    - [ ] sad

- [ ] test DELETE
    - [ ] happy
    - [ ] sad

**Comment by JustinTorrance** [comment]
Back-end is complete!
